-- Sean McGinty <newfolderlocation@gmail.com> 28/08/2021
-- Generated with JS scripts from the google docs.

-- Insert voting categories
INSERT INTO categories (catName, descriptor) VALUES ('Best Barbie (Protagonist)', 'Which Barbie is the best?'), ('Best Couple', 'Who do you think is the best couple?'), ('Best Animal Sidekick', 'Who do you think is the best animal sidekick?'), ('Best Villain', 'Who do you think is the best villain?'), ('Best Song', 'What do you think is the best song?'), ('Best Dress', 'What do you think is the best dress?'), ('Best Scene', 'What do you think is the best scene?'), ('Worst/Most Cursed moment/scene', 'What do you think is the worst/most cursed moment/scene?');

-- Insert voting nominations
INSERT INTO nominations (nomName, nomCat) VALUES ('Corinne (Three Musketeers)', 1), ('Anneliese (Princess and the Pauper)', 1), ('Barbie (Star Light Adventures)', 1), ('Blair Willows (Charm School)', 1), ('Elina (Fairytopia franchise)', 1), ('Kristyn (Pink Shoes)', 1), ('Ro (Island Princess)', 1), ('Alexa and Liana (the Diamond Castle)', 2), ('Albrecht and Hilarion (Pink Shoes)', 2), ('Barbie and Sal-Lee (Star Light Adventure)', 2), ('Elina and Sunburst (Magic of the Rainbow)', 2), ('Barbie and Ken (Dolphin Magic)', 2), ('Arrrlene and The Captain (Barbie and Chelsea: The Lost Birthday)', 2), ('Derek and Genevieve (12 Dancing Princesses)', 2), ('Bibble (Fairytopia)', 3), ('Miette (The Three Musketeers)', 3), ('Azul (Island Princess)', 3), ('Pupcorn (Starlight Adventure)', 3), ('Lazlo (Spy Squad)', 3), ('Tika (Barbie as the Island Princess)', 3), ('Wolfie (PatP)', 3), ('Preminger (Princess and the Pauper) ', 4), ('Raquelle (Barbie universe)', 4), ('Portia (Princess Charm School)', 4), ("The two headmasters (Rock N\' Royals)", 4), ('Laverna (Fairytopia Saga)', 4), ('Paedophile Fish (A Mermaid Tale 2)', 4), ('Patricia (Spy Squad)', 4), ('How Could I Refuse (Princess and the Pauper)', 5), ('A Girl Like You (Princess and the Pauper)', 5), ('All For One (Barbie and the Three Musketeers)', 5), ('I Need to Know (Island Princess)', 5), ('Written in your Heart (Princess and the Pauper)', 5), ('King of the Kingdom (Barbie Princess Adventure)', 5), ('12 Dancing Princesses Theme (12 Dancing Princesses)', 5), ('All four ballgowns in Three Musketeers', 6), ("Mariposa\'s dress", 6), ("Elina\'s outfit in Mermaidia", 6), ('Nori (Mermaidia)', 6), ("Dame Devin\'s gold frilly dress (Princess Charm School)", 6), ("Giselle\'s Outfit (Pink Shoes)", 6), ("Alexa\'s second dress from Secret Door", 6), ("Ken Kidnapping Scene (Fairy Secret)", 7), ('Island Princess Lullaby Scene (Island Princess)', 7), ("The Cat\'s Meow scene (Princess and the Pauper)", 7), ('The ballroom fight (Three Musketeers)', 7), ('Lotus Blossoming Scene (Fairytopia: Magic of the Rainbow)', 7), ('Lefting, leftaroo (Mermaidia)', 7), ('Ice Queen vs Barbie Ballet Off (Pink Shoes)', 7), ('Any with that wacky dragon sidekick (Barbie: Rapunzel)', 8), ('The Barbie Diaries (The Barbie Diaries)', 8), ('\"Better late than never!\" (Pink Shoes)', 8), ('Like 99% of Secret Door (Secret Door)', 8), ('The Keypad Vault Scene (Charm School)', 8), ('That one scene of those two dogs dancing in a god forsaken way (Diamond Castle)', 8), ('Tiger Rap (Barbie and Chelsea: The Lost Birthday)', 8);

-- Insert my votes
INSERT INTO votes (nomCat, nomName1, nomName2, nomName3, nomName4, nomName5, nomName6, nomName7, userid) VALUES ('1', '3', '2', '5', '1', '4', '6', '7', '647976088894439454'), ('2', '1', '5', '3', '2', '6', '7', '4', '647976088894439454'), ('3', '1', '4', '6', '2', '3', '7', '5', '647976088894439454'), ('4', '1', '6', '2', '3', '5', '4', '7', '647976088894439454'), ('5', '1', '3', '2', '5', '4', '6', '7', '647976088894439454'), ('6', '4', '3', '1', '2', '6', '5', '7', '647976088894439454'), ('7', '3', '4', '5', '6', '7', '1', '2', '647976088894439454'), ('8', '5', '2', '3', '7', '6', '4', '1', '647976088894439454');
